name: Update language statistics

on:
  schedule:
    - cron: '0 0 * * *'     # every day at midnight UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update README language stats
        uses: DimaTc/readme-stats-updater@v0.1.1
        with:
          filename: README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update language stats" || echo "No changes"
          git push
